#ifndef MOUSE_DRIVER_H
#define MOUSE_DRIVER_H

#include "Screen.h"

/**
 * @brief
 *
 */
typedef struct {
  int x_pos;
  int y_pos;
  int max_x, max_y;
  int least_x, least_y;
  int f_device;
  char* device;
} MouseDriver;

/**
 * @brief Initiates the mouse driver settings
 *
 */
void InitMouseDriver(void);

/**
 * @brief Disposes all content generated by the driver
 *
 */
void DisposeMouseDriver(void);

/**
 * @brief Handles the SIGINT signal to free any resource allocated by the driver
 *
 * @param signal
 */
void HandleMouseCleanup(int signal);

/**
 * @brief Get the Mouse Driver object
 *
 * @return MouseDriver*
 */
MouseDriver* GetMouseDriver(void);

/**
 * @brief Get the Mouse object
 *
 */
void GetMouse(Screen* screen);

#endif  // MOUSE_DRIVER_H