#ifndef MOUSE_DRIVER_H
#define MOUSE_DRIVER_H

/**
 * @brief
 *
 */
typedef struct {
  int x_pos;
  int y_pos;
  int f_device;
  char* device;
} MouseDriver;

/**
 * @brief Initiates the mouse driver settings
 *
 */
void InitMouseDriver(void);

/**
 * @brief Disposes all content generated by the driver
 *
 */
void DisposeMouseDriver(void);

/**
 * @brief Handles the SIGINT signal to free any resource allocated by the driver
 *
 * @param signal
 */
void HandleMouseCleanup(int signal);

/**
 * @brief Get the Mouse object
 *
 */
void GetMouse(void);

#endif  // MOUSE_DRIVER_H